language: java

sudo: false

os:
 - linux

jdk:
  - oraclejdk8


after_success:
 - mvn sonar:sonar -Dsonar.host.url=${SonarQubeURL} -Dsonar.login=${SonarQube} -Dsonar.github.oauth=b3f69430f719a132a11c79f6186f2594fe8f7b17